# Generated by Django 5.2.4 on 2025-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todoitem_created_at_todoitem_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
